import type { Topic } from '@/types/topic';

export const MOCK_GRAMMAR_TOPICS: Topic[] = [
  {
    id: 'present-tense',
    title: 'Present Tense',
    description: 'Learn about simple and continuous present tense',
    progress: 75,
    exercises: 10,
    completed: 7,
    type: 'grammar',
  },
  {
    id: 'past-tense',
    title: 'Past Tense',
    description: 'Master regular and irregular past tense verbs',
    progress: 50,
    exercises: 12,
    completed: 6,
    type: 'grammar',
  },
  {
    id: 'conditionals',
    title: 'Conditionals',
    description: 'Practice zero, first, and second conditionals',
    progress: 25,
    exercises: 8,
    completed: 2,
    type: 'grammar',
  },
];

export const MOCK_VOCABULARY_TOPICS: Topic[] = [
  {
    id: 'software-development-basics',
    title: 'Software Development Basics',
    description: 'Essential vocabulary related to coding, debugging, and development processes.',
    progress: 60,
    exercises: 15,
    completed: 9,
    type: 'vocabulary',
  },
  {
    id: 'reporting-issues-debugging',
    title: 'Reporting Issues & Debugging',
    description: 'How to describe problems, report bugs, and discuss solutions.',
    progress: 40,
    exercises: 20,
    completed: 8,
    type: 'vocabulary',
  },
  {
    id: 'technical-tools-platforms',
    title: 'Technical Tools & Platforms',
    description: 'Terms related to IDEs, version control (Git), databases, and cloud services.',
    progress: 30,
    exercises: 25,
    completed: 7,
    type: 'vocabulary',
  },
  {
    id: 'it-security-best-practices',
    title: 'IT Security & Best Practices',
    description: 'Basic terms for cybersecurity, data protection, and secure coding.',
    progress: 20,
    exercises: 10,
    completed: 2,
    type: 'vocabulary',
  },
  {
    id: 'job-related-small-talk',
    title: 'Job-Related Small Talk',
    description: 'Common topics to discuss with colleagues, such as hobbies, interests, and work culture.',
    progress: 30,
    exercises: 30,
    completed: 9,
    type: 'vocabulary',
  },
];

export const MOCK_READING_TOPICS: Topic[] = [
  {
    id: 'academic-reading',
    title: 'Academic Articles',
    description: 'Practice reading and comprehending academic texts',
    progress: 40,
    exercises: 10,
    completed: 4,
    type: 'reading',
  },
  {
    id: 'news-articles',
    title: 'News Articles',
    description: 'Read and analyze current news articles',
    progress: 60,
    exercises: 15,
    completed: 9,
    type: 'reading',
  },
];

export const MOCK_WRITING_TOPICS: Topic[] = [
  {
    id: 'writing-a-professional-email-to-hr',
    title: 'Writing a Professional Email to HR',
    description: 'Ask about onboarding, vacation policies, or benefits.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'writing',
  },
  {
    id: 'reporting-an-incident-on-slack',
    title: 'Reporting an Incident on Slack/Teams',
    description: 'Alert the team about a server outage or a broken deployment.',
    progress: 45,
    exercises: 10,
    completed: 4,
    type: 'writing',
  },
  {
    id: 'messaging-a-teammate-about-a-blocker',
    title: 'Messaging a Teammate About a Blocker',
    description: 'Ask for help efficiently without wasting time.',
    progress: 37.5,
    exercises: 8,
    completed: 3,
    type: 'writing',
  },
];

export const MOCK_SPEAKING_TOPICS: Topic[] = [
  {
    id: 'interview-with-hr',
    title: 'Interview with HR',
    description: 'Answer common HR questions about your background, skills, and motivation for joining the company.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'speaking',
  },
  {
    id: 'technical-interview-with-a-senior-engineer',
    title: 'Technical Interview with a Senior Engineer',
    description: 'Explain your approach to solving coding challenges and discuss past projects.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'speaking',
  },
  {
    id: 'code-review-discussion',
    title: 'Code Review Discussion',
    description: 'Receive feedback from a senior developer and respond professionally.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'speaking',
  },
  {
    id: 'presenting-a-feature-you-built',
    title: 'Presenting a Feature You Built',
    description: 'Walk through your code and functionality to your team.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'speaking',
  },
  {
    id: 'explaining-a-bug-to-a-non-Technical-manager',
    title: 'Explaining a Bug to a Non-Technical Manager',
    description: 'Describe a technical issue in simple terms and propose a solution.',
    progress: 16.7,
    exercises: 12,
    completed: 2,
    type: 'speaking',
  },
];
